/**
 * Prisma Seed Data
 *
 * 由 convert-sql-to-seed.ts 脚本自动生成
 * 生成时间: 2025-12-03T10:32:20.397Z
 *
 * 运行方式: npx prisma db seed
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('开始导入种子数据...');

  // sys_tenant_package (租户套餐表)
  await prisma.sysTenantPackage.createMany({
    data: [
      {
        packageId: 1,
        packageName: '基础套餐',
        menuIds: '1,2,3,4,100,101,102,103,104,105,106,107,108,109,110,112,113,114,115,116,117,500,501,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060',
        menuCheckStrictly: true,
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        remark: '基础套餐，包含所有菜单权限',
      },
    ],
    skipDuplicates: true,
  });

  // sys_tenant (租户表)
  await prisma.sysTenant.createMany({
    data: [
      {
        id: 1,
        tenantId: '000000',
        contactUserName: 'admin',
        contactPhone: '15888888888',
        companyName: '管理组',
        licenseNumber: null,
        address: null,
        intro: '系统默认租户，不可删除',
        domain: null,
        packageId: null,
        expireTime: null,
        accountCount: -1,
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        remark: '超级管理员租户',
      },
    ],
    skipDuplicates: true,
  });

  // sys_client (客户端表)
  await prisma.sysClient.createMany({
    data: [
      {
        id: 1,
        clientId: 'e5cd7e4891bf95d1d19206ce24a7b32e',
        clientKey: 'pc',
        clientSecret: 'pc123',
        grantTypeList: 'password,social',
        deviceType: 'pc',
        activeTimeout: 1800,
        timeout: 86400,
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
      },
      {
        id: 2,
        clientId: '428a8310a3c9c5eb0a7c4c9d4b3d0c37',
        clientKey: 'app',
        clientSecret: 'app123',
        grantTypeList: 'password,social',
        deviceType: 'app',
        activeTimeout: 1800,
        timeout: 86400,
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
      },
    ],
    skipDuplicates: true,
  });

  // sys_dict_type
  await prisma.sysDictType.createMany({
    data: [
      {
        dictId: 1,
        dictName: '用户性别',
        dictType: 'sys_user_sex',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '用户性别列表',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictId: 2,
        dictName: '菜单状态',
        dictType: 'sys_show_hide',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '菜单状态列表',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictId: 3,
        dictName: '系统开关',
        dictType: 'sys_normal_disable',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '系统开关列表',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictId: 4,
        dictName: '任务状态',
        dictType: 'sys_job_status',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '任务状态列表',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictId: 5,
        dictName: '任务分组',
        dictType: 'sys_job_group',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '任务分组列表',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictId: 6,
        dictName: '系统是否',
        dictType: 'sys_yes_no',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '系统是否列表',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictId: 7,
        dictName: '通知类型',
        dictType: 'sys_notice_type',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '通知类型列表',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictId: 8,
        dictName: '通知状态',
        dictType: 'sys_notice_status',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '通知状态列表',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictId: 9,
        dictName: '操作类型',
        dictType: 'sys_oper_type',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '操作类型列表',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictId: 10,
        dictName: '系统状态',
        dictType: 'sys_common_status',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '登录状态列表',
        delFlag: '0',
        tenantId: '000000',
      },
    ],
    skipDuplicates: true,
  });

  // sys_dict_data
  await prisma.sysDictData.createMany({
    data: [
      {
        dictCode: 1,
        dictSort: 1,
        dictLabel: '男',
        dictValue: '0',
        dictType: 'sys_user_sex',
        cssClass: '',
        listClass: '',
        isDefault: 'Y',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '性别男',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 2,
        dictSort: 2,
        dictLabel: '女',
        dictValue: '1',
        dictType: 'sys_user_sex',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '性别女',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 3,
        dictSort: 3,
        dictLabel: '未知',
        dictValue: '2',
        dictType: 'sys_user_sex',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '性别未知',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 4,
        dictSort: 1,
        dictLabel: '显示',
        dictValue: '0',
        dictType: 'sys_show_hide',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '显示菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 5,
        dictSort: 2,
        dictLabel: '隐藏',
        dictValue: '1',
        dictType: 'sys_show_hide',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '隐藏菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 6,
        dictSort: 1,
        dictLabel: '正常',
        dictValue: '0',
        dictType: 'sys_normal_disable',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '正常状态',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 7,
        dictSort: 2,
        dictLabel: '停用',
        dictValue: '1',
        dictType: 'sys_normal_disable',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '停用状态',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 8,
        dictSort: 1,
        dictLabel: '正常',
        dictValue: '0',
        dictType: 'sys_job_status',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '正常状态',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 9,
        dictSort: 2,
        dictLabel: '暂停',
        dictValue: '1',
        dictType: 'sys_job_status',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '停用状态',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 10,
        dictSort: 1,
        dictLabel: '默认',
        dictValue: 'DEFAULT',
        dictType: 'sys_job_group',
        cssClass: '',
        listClass: '',
        isDefault: 'Y',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '默认分组',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 11,
        dictSort: 2,
        dictLabel: '系统',
        dictValue: 'SYSTEM',
        dictType: 'sys_job_group',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '系统分组',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 12,
        dictSort: 1,
        dictLabel: '是',
        dictValue: 'Y',
        dictType: 'sys_yes_no',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '系统默认是',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 13,
        dictSort: 2,
        dictLabel: '否',
        dictValue: 'N',
        dictType: 'sys_yes_no',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '系统默认否',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 14,
        dictSort: 1,
        dictLabel: '通知',
        dictValue: '1',
        dictType: 'sys_notice_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'Y',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '通知',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 15,
        dictSort: 2,
        dictLabel: '公告',
        dictValue: '2',
        dictType: 'sys_notice_type',
        cssClass: '',
        listClass: 'success',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '公告',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 16,
        dictSort: 1,
        dictLabel: '正常',
        dictValue: '0',
        dictType: 'sys_notice_status',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '正常状态',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 17,
        dictSort: 2,
        dictLabel: '关闭',
        dictValue: '1',
        dictType: 'sys_notice_status',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '关闭状态',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 18,
        dictSort: 99,
        dictLabel: '其他',
        dictValue: '0',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '其他操作',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 19,
        dictSort: 1,
        dictLabel: '新增',
        dictValue: '1',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '新增操作',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 20,
        dictSort: 2,
        dictLabel: '修改',
        dictValue: '2',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '修改操作',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 21,
        dictSort: 3,
        dictLabel: '删除',
        dictValue: '3',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '删除操作',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 22,
        dictSort: 4,
        dictLabel: '授权',
        dictValue: '4',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '授权操作',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 23,
        dictSort: 5,
        dictLabel: '导出',
        dictValue: '5',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '导出操作',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 24,
        dictSort: 6,
        dictLabel: '导入',
        dictValue: '6',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '导入操作',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 25,
        dictSort: 7,
        dictLabel: '强退',
        dictValue: '7',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '强退操作',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 26,
        dictSort: 8,
        dictLabel: '生成代码',
        dictValue: '8',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '生成操作',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 27,
        dictSort: 9,
        dictLabel: '清空数据',
        dictValue: '9',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '清空操作',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 28,
        dictSort: 1,
        dictLabel: '成功',
        dictValue: '0',
        dictType: 'sys_common_status',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '正常状态',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        dictCode: 29,
        dictSort: 2,
        dictLabel: '失败',
        dictValue: '1',
        dictType: 'sys_common_status',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '停用状态',
        delFlag: '0',
        tenantId: '000000',
      },
    ],
    skipDuplicates: true,
  });

  // sys_config
  await prisma.sysConfig.createMany({
    data: [
      {
        configId: 1,
        configName: '主框架页-默认皮肤样式名称',
        configKey: 'sys.index.skinName',
        configValue: 'skin-blue',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '蓝色 skin-blue、绿色 skin-green、紫色 skin-purple、红色 skin-red、黄色 skin-yellow',
        status: '0',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        configId: 2,
        configName: '用户管理-账号初始密码',
        configKey: 'sys.user.initPassword',
        configValue: '123456',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '初始化密码 123456',
        status: '0',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        configId: 3,
        configName: '主框架页-侧边栏主题',
        configKey: 'sys.index.sideTheme',
        configValue: 'theme-dark',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '深色主题theme-dark，浅色主题theme-light',
        status: '0',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        configId: 4,
        configName: '账号自助-验证码开关',
        configKey: 'sys.account.captchaEnabled',
        configValue: 'true',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '是否开启验证码功能（true开启，false关闭）',
        status: '0',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        configId: 5,
        configName: '账号自助-是否开启用户注册功能',
        configKey: 'sys.account.registerUser',
        configValue: 'false',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '是否开启注册用户功能（true开启，false关闭）',
        status: '0',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        configId: 6,
        configName: '用户登录-黑名单列表',
        configKey: 'sys.login.blackIPList',
        configValue: '',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '设置登录IP黑名单限制，多个匹配项以;分隔，支持匹配（*通配、网段）',
        status: '0',
        delFlag: '0',
        tenantId: '000000',
      },
    ],
    skipDuplicates: true,
  });

  // sys_dept
  await prisma.sysDept.createMany({
    data: [
      {
        deptId: 100,
        parentId: 0,
        ancestors: '0',
        deptName: 'nest-admin科技',
        orderNum: 0,
        leader: 'nest-admin',
        phone: '15888888888',
        email: 'ry@qq.com',
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: null,
        tenantId: '000000',
      },
      {
        deptId: 101,
        parentId: 100,
        ancestors: '0,100',
        deptName: '深圳总公司',
        orderNum: 1,
        leader: 'nest-admin',
        phone: '15888888888',
        email: 'ry@qq.com',
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: null,
        tenantId: '000000',
      },
      {
        deptId: 102,
        parentId: 100,
        ancestors: '0,100',
        deptName: '长沙分公司',
        orderNum: 2,
        leader: 'nest-admin',
        phone: '15888888888',
        email: 'ry@qq.com',
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: null,
        tenantId: '000000',
      },
      {
        deptId: 103,
        parentId: 101,
        ancestors: '0,100,101',
        deptName: '研发部门',
        orderNum: 1,
        leader: 'nest-admin',
        phone: '15888888888',
        email: 'ry@qq.com',
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: null,
        tenantId: '000000',
      },
      {
        deptId: 104,
        parentId: 101,
        ancestors: '0,100,101',
        deptName: '市场部门',
        orderNum: 2,
        leader: 'nest-admin',
        phone: '15888888888',
        email: 'ry@qq.com',
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: null,
        tenantId: '000000',
      },
      {
        deptId: 105,
        parentId: 101,
        ancestors: '0,100,101',
        deptName: '测试部门',
        orderNum: 3,
        leader: 'nest-admin',
        phone: '15888888888',
        email: 'ry@qq.com',
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: null,
        tenantId: '000000',
      },
      {
        deptId: 106,
        parentId: 101,
        ancestors: '0,100,101',
        deptName: '财务部门',
        orderNum: 4,
        leader: 'nest-admin',
        phone: '15888888888',
        email: 'ry@qq.com',
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: null,
        tenantId: '000000',
      },
      {
        deptId: 107,
        parentId: 101,
        ancestors: '0,100,101',
        deptName: '运维部门',
        orderNum: 5,
        leader: 'nest-admin',
        phone: '15888888888',
        email: 'ry@qq.com',
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: null,
        tenantId: '000000',
      },
      {
        deptId: 108,
        parentId: 102,
        ancestors: '0,100,102',
        deptName: '市场部门',
        orderNum: 1,
        leader: 'nest-admin',
        phone: '15888888888',
        email: 'ry@qq.com',
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: null,
        tenantId: '000000',
      },
      {
        deptId: 109,
        parentId: 102,
        ancestors: '0,100,102',
        deptName: '财务部门',
        orderNum: 2,
        leader: 'nest-admin',
        phone: '15888888888',
        email: 'ry@qq.com',
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: null,
        tenantId: '000000',
      },
    ],
    skipDuplicates: true,
  });

  // sys_post
  await prisma.sysPost.createMany({
    data: [
      {
        postId: 1,
        postCode: 'ceo',
        postName: '董事长',
        postSort: 1,
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        postId: 2,
        postCode: 'se',
        postName: '项目经理',
        postSort: 2,
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        postId: 3,
        postCode: 'hr',
        postName: '人力资源',
        postSort: 3,
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        postId: 4,
        postCode: 'user',
        postName: '普通员工',
        postSort: 4,
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
    ],
    skipDuplicates: true,
  });

  // sys_role
  await prisma.sysRole.createMany({
    data: [
      {
        roleId: 1,
        roleName: '超级管理员',
        roleKey: 'admin',
        roleSort: 1,
        dataScope: '1',
        menuCheckStrictly: true,
        deptCheckStrictly: true,
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '超级管理员',
        tenantId: '000000',
      },
      {
        roleId: 2,
        roleName: '普通角色',
        roleKey: 'common',
        roleSort: 2,
        dataScope: '2',
        menuCheckStrictly: true,
        deptCheckStrictly: true,
        status: '0',
        delFlag: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '普通角色',
        tenantId: '000000',
      },
    ],
    skipDuplicates: true,
  });

  // sys_menu
  await prisma.sysMenu.createMany({
    data: [
      {
        menuId: 1,
        menuName: '系统管理',
        parentId: 0,
        orderNum: 1,
        path: 'system',
        component: null,
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'system',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '系统管理目录',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 2,
        menuName: '系统监控',
        parentId: 0,
        orderNum: 2,
        path: 'monitor',
        component: null,
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'monitor',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '系统监控目录',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 3,
        menuName: '系统工具',
        parentId: 0,
        orderNum: 3,
        path: 'tool',
        component: null,
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'tool',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '系统工具目录',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 4,
        menuName: 'nest-admin官网',
        parentId: 0,
        orderNum: 4,
        path: 'https://nest-admin.dooring.vip',
        component: null,
        query: '',
        isFrame: '0',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'guide',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: 'nest-admin官网地址',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 100,
        menuName: '用户管理',
        parentId: 1,
        orderNum: 1,
        path: 'user',
        component: 'system/user/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:user:list',
        icon: 'user',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '用户管理菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 101,
        menuName: '角色管理',
        parentId: 1,
        orderNum: 2,
        path: 'role',
        component: 'system/role/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:role:list',
        icon: 'peoples',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '角色管理菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 102,
        menuName: '菜单管理',
        parentId: 1,
        orderNum: 3,
        path: 'menu',
        component: 'system/menu/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:menu:list',
        icon: 'tree-table',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '菜单管理菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 103,
        menuName: '部门管理',
        parentId: 1,
        orderNum: 4,
        path: 'dept',
        component: 'system/dept/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:dept:list',
        icon: 'tree',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '部门管理菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 104,
        menuName: '岗位管理',
        parentId: 1,
        orderNum: 5,
        path: 'post',
        component: 'system/post/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:post:list',
        icon: 'post',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '岗位管理菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 105,
        menuName: '字典管理',
        parentId: 1,
        orderNum: 6,
        path: 'dict',
        component: 'system/dict/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:dict:list',
        icon: 'dict',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '字典管理菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 106,
        menuName: '参数设置',
        parentId: 1,
        orderNum: 7,
        path: 'config',
        component: 'system/config/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:config:list',
        icon: 'edit',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '参数设置菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 107,
        menuName: '通知公告',
        parentId: 1,
        orderNum: 8,
        path: 'notice',
        component: 'system/notice/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:notice:list',
        icon: 'message',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '通知公告菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 108,
        menuName: '日志管理',
        parentId: 1,
        orderNum: 9,
        path: 'log',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'log',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '日志管理菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 109,
        menuName: '在线用户',
        parentId: 2,
        orderNum: 1,
        path: 'online',
        component: 'monitor/online/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:online:list',
        icon: 'online',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '在线用户菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 110,
        menuName: '定时任务',
        parentId: 2,
        orderNum: 2,
        path: 'job',
        component: 'monitor/job/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:job:list',
        icon: 'job',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '定时任务菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 111,
        menuName: '数据监控',
        parentId: 2,
        orderNum: 3,
        path: 'druid',
        component: 'monitor/druid/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:druid:list',
        icon: 'druid',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '数据监控菜单',
        delFlag: '1',
        tenantId: '000000',
      },
      {
        menuId: 112,
        menuName: '服务监控',
        parentId: 2,
        orderNum: 4,
        path: 'server',
        component: 'monitor/server/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:server:list',
        icon: 'server',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '服务监控菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 113,
        menuName: '缓存监控',
        parentId: 2,
        orderNum: 5,
        path: 'cache',
        component: 'monitor/cache/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:cache:list',
        icon: 'redis',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '缓存监控菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 114,
        menuName: '缓存列表',
        parentId: 2,
        orderNum: 6,
        path: 'cacheList',
        component: 'monitor/cache/list',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:cache:list',
        icon: 'redis-list',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '缓存列表菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 115,
        menuName: '表单构建',
        parentId: 3,
        orderNum: 1,
        path: 'build',
        component: 'tool/build/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'tool:build:list',
        icon: 'build',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '表单构建菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 116,
        menuName: '代码生成',
        parentId: 3,
        orderNum: 2,
        path: 'gen',
        component: 'tool/gen/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'tool:gen:list',
        icon: 'code',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '代码生成菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 117,
        menuName: '系统接口',
        parentId: 3,
        orderNum: 3,
        path: 'swagger',
        component: 'tool/swagger/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'tool:swagger:list',
        icon: 'swagger',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '系统接口菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 500,
        menuName: '操作日志',
        parentId: 108,
        orderNum: 1,
        path: 'operlog',
        component: 'monitor/operlog/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:list',
        icon: 'form',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '操作日志菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 501,
        menuName: '登录日志',
        parentId: 108,
        orderNum: 2,
        path: 'logininfor',
        component: 'monitor/logininfor/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:list',
        icon: 'logininfor',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '登录日志菜单',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1000,
        menuName: '用户查询',
        parentId: 100,
        orderNum: 1,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1001,
        menuName: '用户新增',
        parentId: 100,
        orderNum: 2,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:add',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1002,
        menuName: '用户修改',
        parentId: 100,
        orderNum: 3,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:edit',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1003,
        menuName: '用户删除',
        parentId: 100,
        orderNum: 4,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1004,
        menuName: '用户导出',
        parentId: 100,
        orderNum: 5,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:export',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1005,
        menuName: '用户导入',
        parentId: 100,
        orderNum: 6,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:import',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1006,
        menuName: '重置密码',
        parentId: 100,
        orderNum: 7,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:resetPwd',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1007,
        menuName: '角色查询',
        parentId: 101,
        orderNum: 1,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1008,
        menuName: '角色新增',
        parentId: 101,
        orderNum: 2,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:add',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1009,
        menuName: '角色修改',
        parentId: 101,
        orderNum: 3,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:edit',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1010,
        menuName: '角色删除',
        parentId: 101,
        orderNum: 4,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1011,
        menuName: '角色导出',
        parentId: 101,
        orderNum: 5,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:export',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1012,
        menuName: '菜单查询',
        parentId: 102,
        orderNum: 1,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1013,
        menuName: '菜单新增',
        parentId: 102,
        orderNum: 2,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:add',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1014,
        menuName: '菜单修改',
        parentId: 102,
        orderNum: 3,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:edit',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1015,
        menuName: '菜单删除',
        parentId: 102,
        orderNum: 4,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1016,
        menuName: '部门查询',
        parentId: 103,
        orderNum: 1,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1017,
        menuName: '部门新增',
        parentId: 103,
        orderNum: 2,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:add',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1018,
        menuName: '部门修改',
        parentId: 103,
        orderNum: 3,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:edit',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1019,
        menuName: '部门删除',
        parentId: 103,
        orderNum: 4,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1020,
        menuName: '岗位查询',
        parentId: 104,
        orderNum: 1,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1021,
        menuName: '岗位新增',
        parentId: 104,
        orderNum: 2,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:add',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1022,
        menuName: '岗位修改',
        parentId: 104,
        orderNum: 3,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:edit',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1023,
        menuName: '岗位删除',
        parentId: 104,
        orderNum: 4,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1024,
        menuName: '岗位导出',
        parentId: 104,
        orderNum: 5,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:export',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1025,
        menuName: '字典查询',
        parentId: 105,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1026,
        menuName: '字典新增',
        parentId: 105,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:add',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1027,
        menuName: '字典修改',
        parentId: 105,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:edit',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1028,
        menuName: '字典删除',
        parentId: 105,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1029,
        menuName: '字典导出',
        parentId: 105,
        orderNum: 5,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:export',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1030,
        menuName: '参数查询',
        parentId: 106,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1031,
        menuName: '参数新增',
        parentId: 106,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:add',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1032,
        menuName: '参数修改',
        parentId: 106,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:edit',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1033,
        menuName: '参数删除',
        parentId: 106,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1034,
        menuName: '参数导出',
        parentId: 106,
        orderNum: 5,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:export',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1035,
        menuName: '公告查询',
        parentId: 107,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1036,
        menuName: '公告新增',
        parentId: 107,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:add',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1037,
        menuName: '公告修改',
        parentId: 107,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:edit',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1038,
        menuName: '公告删除',
        parentId: 107,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1039,
        menuName: '操作查询',
        parentId: 500,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1040,
        menuName: '操作删除',
        parentId: 500,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1041,
        menuName: '日志导出',
        parentId: 500,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:export',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1042,
        menuName: '登录查询',
        parentId: 501,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1043,
        menuName: '登录删除',
        parentId: 501,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1044,
        menuName: '日志导出',
        parentId: 501,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:export',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1045,
        menuName: '账户解锁',
        parentId: 501,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:unlock',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1046,
        menuName: '在线查询',
        parentId: 109,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:online:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1047,
        menuName: '批量强退',
        parentId: 109,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:online:batchLogout',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1048,
        menuName: '单条强退',
        parentId: 109,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:online:forceLogout',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1049,
        menuName: '任务查询',
        parentId: 110,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1050,
        menuName: '任务新增',
        parentId: 110,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:add',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1051,
        menuName: '任务修改',
        parentId: 110,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:edit',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1052,
        menuName: '任务删除',
        parentId: 110,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1053,
        menuName: '状态修改',
        parentId: 110,
        orderNum: 5,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:changeStatus',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1054,
        menuName: '任务导出',
        parentId: 110,
        orderNum: 6,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:export',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1055,
        menuName: '生成查询',
        parentId: 116,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:query',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1056,
        menuName: '生成修改',
        parentId: 116,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:edit',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1057,
        menuName: '生成删除',
        parentId: 116,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:remove',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1058,
        menuName: '导入代码',
        parentId: 116,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:import',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1059,
        menuName: '预览代码',
        parentId: 116,
        orderNum: 5,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:preview',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
      {
        menuId: 1060,
        menuName: '生成代码',
        parentId: 116,
        orderNum: 6,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:code',
        icon: '#',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: '0',
        tenantId: '000000',
      },
    ],
    skipDuplicates: true,
  });

  // sys_user
  await prisma.sysUser.createMany({
    data: [
      {
        userId: 1,
        deptId: 103,
        userName: 'admin',
        nickName: 'nest-admin',
        userType: '00',
        email: 'ry@163.com',
        phonenumber: '15888888888',
        sex: '1',
        password: '$2b$10$UrJrjy0kxyrTO1UvhRVsvex35mB1s1jzAraIA9xtzPmlLmRtZXEXS',
        status: '0',
        delFlag: '0',
        loginIp: '127.0.0.1',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '管理员',
        avatar: '',
        loginDate: null,
        tenantId: '000000',
      },
      {
        userId: 2,
        deptId: 105,
        userName: 'ry',
        nickName: 'nest-admin',
        userType: '00',
        email: 'ry@qq.com',
        phonenumber: '15666666666',
        sex: '1',
        password: '$2b$10$UrJrjy0kxyrTO1UvhRVsvex35mB1s1jzAraIA9xtzPmlLmRtZXEXS',
        status: '0',
        delFlag: '0',
        loginIp: '127.0.0.1',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '测试员',
        avatar: '',
        loginDate: null,
        tenantId: '000000',
      },
    ],
    skipDuplicates: true,
  });

  // sys_notice
  await prisma.sysNotice.createMany({
    data: [
      {
        noticeId: 1,
        noticeTitle: '温馨提醒：2018-07-01 nest-admin新版本发布啦',
        noticeType: '2',
        noticeContent: '新版本内容',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        delFlag: '0',
        remark: null,
        tenantId: '000000',
      },
      {
        noticeId: 2,
        noticeTitle: '维护通知：2018-07-01 nest-admin系统凌晨维护',
        noticeType: '1',
        noticeContent: '维护内容',
        status: '0',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        delFlag: '0',
        remark: null,
        tenantId: '000000',
      },
    ],
    skipDuplicates: true,
  });

  // sys_job
  await prisma.sysJob.createMany({
    data: [
      {
        jobId: 1,
        jobName: '系统默认（无参）',
        jobGroup: 'DEFAULT',
        invokeTarget: 'task.noParams',
        cronExpression: '0/10 * * * * ?',
        misfirePolicy: '3',
        concurrent: '1',
        status: '1',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        tenantId: '000000',
      },
      {
        jobId: 2,
        jobName: '系统默认（有参）',
        jobGroup: 'DEFAULT',
        invokeTarget: 'task.params(\'ry\')',
        cronExpression: '0/15 * * * * ?',
        misfirePolicy: '3',
        concurrent: '1',
        status: '1',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        tenantId: '000000',
      },
      {
        jobId: 3,
        jobName: '系统默认（多参）',
        jobGroup: 'DEFAULT',
        invokeTarget: 'task.multipleParams(\'ry\', true, 2000L, 316.50D, 100)',
        cronExpression: '0/20 * * * * ?',
        misfirePolicy: '3',
        concurrent: '1',
        status: '1',
        createBy: 'admin',
        createTime: new Date('2025-02-28 16:52:10.000000'),
        updateBy: '',
        updateTime: null,
        remark: '',
        tenantId: '000000',
      },
    ],
    skipDuplicates: true,
  });

  // sys_role_dept
  await prisma.sysRoleDept.createMany({
    data: [
      {
        roleId: 2,
        deptId: 100,
      },
      {
        roleId: 2,
        deptId: 101,
      },
      {
        roleId: 2,
        deptId: 105,
      },
    ],
    skipDuplicates: true,
  });

  // sys_role_menu
  await prisma.sysRoleMenu.createMany({
    data: [
      {
        roleId: 2,
        menuId: 1,
      },
      {
        roleId: 2,
        menuId: 2,
      },
      {
        roleId: 2,
        menuId: 3,
      },
      {
        roleId: 2,
        menuId: 4,
      },
      {
        roleId: 2,
        menuId: 100,
      },
      {
        roleId: 2,
        menuId: 101,
      },
      {
        roleId: 2,
        menuId: 102,
      },
      {
        roleId: 2,
        menuId: 103,
      },
      {
        roleId: 2,
        menuId: 104,
      },
      {
        roleId: 2,
        menuId: 105,
      },
      {
        roleId: 2,
        menuId: 106,
      },
      {
        roleId: 2,
        menuId: 107,
      },
      {
        roleId: 2,
        menuId: 108,
      },
      {
        roleId: 2,
        menuId: 109,
      },
      {
        roleId: 2,
        menuId: 110,
      },
      {
        roleId: 2,
        menuId: 111,
      },
      {
        roleId: 2,
        menuId: 112,
      },
      {
        roleId: 2,
        menuId: 113,
      },
      {
        roleId: 2,
        menuId: 114,
      },
      {
        roleId: 2,
        menuId: 115,
      },
      {
        roleId: 2,
        menuId: 116,
      },
      {
        roleId: 2,
        menuId: 117,
      },
      {
        roleId: 2,
        menuId: 500,
      },
      {
        roleId: 2,
        menuId: 501,
      },
      {
        roleId: 2,
        menuId: 1000,
      },
      {
        roleId: 2,
        menuId: 1001,
      },
      {
        roleId: 2,
        menuId: 1002,
      },
      {
        roleId: 2,
        menuId: 1003,
      },
      {
        roleId: 2,
        menuId: 1004,
      },
      {
        roleId: 2,
        menuId: 1005,
      },
      {
        roleId: 2,
        menuId: 1006,
      },
      {
        roleId: 2,
        menuId: 1007,
      },
      {
        roleId: 2,
        menuId: 1008,
      },
      {
        roleId: 2,
        menuId: 1009,
      },
      {
        roleId: 2,
        menuId: 1010,
      },
      {
        roleId: 2,
        menuId: 1011,
      },
      {
        roleId: 2,
        menuId: 1012,
      },
      {
        roleId: 2,
        menuId: 1013,
      },
      {
        roleId: 2,
        menuId: 1014,
      },
      {
        roleId: 2,
        menuId: 1015,
      },
      {
        roleId: 2,
        menuId: 1016,
      },
      {
        roleId: 2,
        menuId: 1017,
      },
      {
        roleId: 2,
        menuId: 1018,
      },
      {
        roleId: 2,
        menuId: 1019,
      },
      {
        roleId: 2,
        menuId: 1020,
      },
      {
        roleId: 2,
        menuId: 1021,
      },
      {
        roleId: 2,
        menuId: 1022,
      },
      {
        roleId: 2,
        menuId: 1023,
      },
      {
        roleId: 2,
        menuId: 1024,
      },
      {
        roleId: 2,
        menuId: 1025,
      },
      {
        roleId: 2,
        menuId: 1026,
      },
      {
        roleId: 2,
        menuId: 1027,
      },
      {
        roleId: 2,
        menuId: 1028,
      },
      {
        roleId: 2,
        menuId: 1029,
      },
      {
        roleId: 2,
        menuId: 1030,
      },
      {
        roleId: 2,
        menuId: 1031,
      },
      {
        roleId: 2,
        menuId: 1032,
      },
      {
        roleId: 2,
        menuId: 1033,
      },
      {
        roleId: 2,
        menuId: 1034,
      },
      {
        roleId: 2,
        menuId: 1035,
      },
      {
        roleId: 2,
        menuId: 1036,
      },
      {
        roleId: 2,
        menuId: 1037,
      },
      {
        roleId: 2,
        menuId: 1038,
      },
      {
        roleId: 2,
        menuId: 1039,
      },
      {
        roleId: 2,
        menuId: 1040,
      },
      {
        roleId: 2,
        menuId: 1041,
      },
      {
        roleId: 2,
        menuId: 1042,
      },
      {
        roleId: 2,
        menuId: 1043,
      },
      {
        roleId: 2,
        menuId: 1044,
      },
      {
        roleId: 2,
        menuId: 1045,
      },
      {
        roleId: 2,
        menuId: 1046,
      },
      {
        roleId: 2,
        menuId: 1047,
      },
      {
        roleId: 2,
        menuId: 1048,
      },
      {
        roleId: 2,
        menuId: 1049,
      },
      {
        roleId: 2,
        menuId: 1050,
      },
      {
        roleId: 2,
        menuId: 1051,
      },
      {
        roleId: 2,
        menuId: 1052,
      },
      {
        roleId: 2,
        menuId: 1053,
      },
      {
        roleId: 2,
        menuId: 1054,
      },
      {
        roleId: 2,
        menuId: 1055,
      },
      {
        roleId: 2,
        menuId: 1056,
      },
      {
        roleId: 2,
        menuId: 1057,
      },
      {
        roleId: 2,
        menuId: 1058,
      },
      {
        roleId: 2,
        menuId: 1059,
      },
      {
        roleId: 2,
        menuId: 1060,
      },
    ],
    skipDuplicates: true,
  });

  // sys_user_post
  await prisma.sysUserPost.createMany({
    data: [
      {
        userId: 1,
        postId: 1,
      },
      {
        userId: 2,
        postId: 2,
      },
    ],
    skipDuplicates: true,
  });

  // sys_user_role
  await prisma.sysUserRole.createMany({
    data: [
      {
        userId: 1,
        roleId: 1,
      },
      {
        userId: 2,
        roleId: 2,
      },
    ],
    skipDuplicates: true,
  });

  console.log('种子数据导入完成!');
}

main()
  .catch((e) => {
    console.error('种子数据导入失败:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
